 # Main language/toolchain
language: csharp

# Mono is not required for this project
mono: none

# Install .NET Core 2.1
dotnet: 2.1

# Run Ubuntu Trusty
dist: trusty

# Disable sudo to enable running inside a container
sudo: false

# Skip the installation step
install: true

# Additional jobs that run after tests
jobs:
  fast_finish: true
  include:

    - stage: Build and Test
      script:
        - dotnet restore
        - dotnet build -c ${BUILD_CONFIG}
        - dotnet test -c ${BUILD_CONFIG} --no-build Didstopia.PDFSharp.Tests
        - dotnet pack -c ${BUILD_CONFIG} --no-build

    - stage: Deploy to MyGet
      script: skip
      deploy:
        provider: script
        script: .scripts/deploy.sh $BUILD_CONFIG $MYGET_API_KEY $MYGET_FEED
        skip_cleanup: true
        on:
          repo: Didstopia/PDFSharp
          branch: development
          tags: false

    - stage: Deploy to NuGet
      script: skip
      deploy:
        provider: script
        script: .scripts/deploy.sh $BUILD_CONFIG $NUGET_API_KEY "" $TRAVIS_TAG
        skip_cleanup: true
        on:
          repo: Didstopia/PDFSharp
          branch: master
          tags: true

    - stage: Deploy to GitHub
      script:
        - dotnet restore /p:PackageVersion=${TRAVIS_TAG#v}
        - dotnet build -c $BUILD_CONFIG /p:PackageVersion=${TRAVIS_TAG#v}
        - dotnet pack -c $BUILD_CONFIG --no-build /p:PackageVersion=${TRAVIS_TAG#v}
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true
        file: "Didstopia.PDFSharp/bin/${BUILD_CONFIG}/*.nupkg"
        skip_cleanup: true
        on:
          repo: Didstopia/PDFSharp
          branch: master
          tags: true
